export const GOOGLE_ADS_ID = "AW-18082628701";
export const SIGNUP_CONVERSION_SEND_TO = `${GOOGLE_ADS_ID}/WkZACIiLpJocEN2IvK5D`;
export const SIGNUP_CONVERSION_VALUE = 1.0;
export const SIGNUP_CONVERSION_CURRENCY = "EUR";
